version: "3.8"

services:
  db:
    image: mysqlcompose
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    volumes:
      - db_data:/var/lib/mysql
  
  backend:
    depends_on:
      - db
    image: flaskcompose
    ports:
      - "5000:5000"
    restart: always
    networks:
      - dockercompose
    volumes:
      - "~/Docker/CursoDocker/docker-compose/6_bind_mount/flask:/app"

networks:
  dockercompose:
volumes:
  db_data: {}