version: "3.8"

services: # dentro de service é onde eu configuro os containers
  db: # container de mysql
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./configs/db.env
    networks:
      - backend

  wordpress: # container do wordpress
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./configs/wp.env
    networks:
      - backend

volumes:
  db_data: {}
networks:
  backend:
    driver: bridge